name: walnuts tests

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch: {}

env:
  CACHE_VERSION: 1

# only run one copy per PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test (${{matrix.cfg.os}}/${{matrix.cfg.compiler}})
    runs-on: ${{matrix.cfg.os}}-${{matrix.cfg.version || 'latest'}}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - os: windows
            compiler: msvc
          - os: windows
            compiler: gcc
          - os: ubuntu
            compiler: gcc
          - os: macos
            version: 26
            compiler: clang

    steps:
      - name: Check out github
        uses: actions/checkout@v7

      - name: Dependency caching
        uses: actions/cache@v5
        id: deps-cache
        with:
          path: ./build/_deps/
          key: ${{ runner.os }}-${{ matrix.cfg.compiler }}-deps-${{ hashFiles('**/CMakeLists.txt') }}-v${{ env.CACHE_VERSION }}

      - name: "Windows: Set up MSVC"
        uses: ilammy/msvc-dev-cmd@v1
        if: matrix.cfg.compiler == 'msvc' && matrix.cfg.os == 'windows'
      - name: "Windows: Set up GCC"
        uses: bwoodsend/setup-winlibs-action@v1
        if: matrix.cfg.compiler == 'gcc' && matrix.cfg.os == 'windows'

      - name: Build
        run: |
          cmake -S . -B build/ -G Ninja -DWALNUTS_BUILD_TESTS=ON -DWALNUTS_BUILD_DOCS=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build build/ --parallel 4 --config RelWithDebInfo

      - name: Run examples
        run: |
          cd build/
          ls -lha examples/
          ./examples/walnuts_api${{ matrix.cfg.os == 'windows' && '.exe' || '' }}
        shell: bash

      - name: Test
        run: |
          cd build/
          ctest --output-on-failure --parallel 4 --repeat until-pass:2 -C RelWithDebInfo
        shell: bash


  build_wheels:
    name: "Python: wheels for ${{ matrix.cfg.os }}"
    runs-on: ${{matrix.cfg.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - os: windows-x86_64
            runs-on: windows-latest
          - os: linux-x86_64
            runs-on: ubuntu-latest
          - os: linux-arm
            runs-on: ubuntu-24.04-arm
          - os: macos-arm
            runs-on: macos-26
          - os: macos-x86_64
            runs-on: macos-26-intel
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Build wheels
        uses: pypa/cibuildwheel@v4.1.0
        env:
           CIBW_ENVIRONMENT_MACOS: >
               MACOSX_DEPLOYMENT_TARGET=15

      - uses: actions/upload-artifact@v7
        with:
          name: cibw-wheels-${{ matrix.cfg.os }}
          path: ./wheelhouse/*.whl

  make_sdist:
    name: "Python: source distribution"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        persist-credentials: false

    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v7
      with:
        name: cibw-sdist
        path: dist/*.tar.gz
