name: walnutpie python

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        description: Should this also upload to PyPI?
        default: false


# only run one copy per PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pytest:
    name: Test (${{ matrix.os.os }} / Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - os: windows
            runs-on: windows-latest
          - os: linux
            runs-on: ubuntu-latest
          - os: macos-arm
            runs-on: macos-26
          - os: macos-x86_64
            runs-on: macos-26-intel

        python-version: ["3.10", "3.14"]

    steps:
      - name: Check out github
        uses: actions/checkout@v7

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: pip install .[test]

      - name: Install additional test dependencies
        if: matrix.os.os != 'macos-x86_64'
        run: pip install .[test-fast]

      - name: BridgeStan cache
        uses: actions/cache@v6
        with:
          path: ~/.bridgestan/
          key: ${{ matrix.os.os }}${{ matrix.os.arch }}-bridgestan-290

      - name: Test
        run: pytest python/

  build_wheels:
    name: "Build wheels for ${{ matrix.cfg.os }}"
    runs-on: ${{matrix.cfg.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - os: windows-x86_64
            runs-on: windows-latest
          - os: linux-x86_64
            runs-on: ubuntu-latest
          - os: linux-arm
            runs-on: ubuntu-24.04-arm
          - os: macos-arm
            runs-on: macos-26
          - os: macos-x86_64
            runs-on: macos-26-intel
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Build wheels
        uses: pypa/cibuildwheel@v4.1.0
        env:
           CIBW_ENVIRONMENT_MACOS: >
               MACOSX_DEPLOYMENT_TARGET=15

      - uses: actions/upload-artifact@v7
        with:
          name: cibw-wheels-${{ matrix.cfg.os }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: "Build source distribution"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        persist-credentials: false

    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v7
      with:
        name: cibw-sdist
        path: dist/*.tar.gz

  publish:
    name: Upload wheels to PyPI
    if: inputs.release || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    needs: [build_sdist, build_wheels]
    environment: release
    permissions:
      id-token: write # OIDC for pypi
    steps:
      - name: Check out github
        uses: actions/checkout@v7

      - name: Download release artifacts
        uses: actions/download-artifact@v8
        with:
          path: wheels
          merge-multiple: true
      - run: ls wheels/
      - name: Upload PyPI wheels
        uses: pypa/gh-action-pypi-publish@v1.14.2
        with:
          packages-dir: wheels/
          skip-existing: true
